# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import discovery_service_pb2 as discovery__service__pb2


class DiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Keepalive = channel.stream_stream(
                '/neptune.Discovery/Keepalive',
                request_serializer=discovery__service__pb2.KeepaliveRequest.SerializeToString,
                response_deserializer=discovery__service__pb2.Servers.FromString,
                )
        self.Register = channel.unary_unary(
                '/neptune.Discovery/Register',
                request_serializer=discovery__service__pb2.Server.SerializeToString,
                response_deserializer=discovery__service__pb2.RegisterResponse.FromString,
                )
        self.Echo = channel.unary_unary(
                '/neptune.Discovery/Echo',
                request_serializer=discovery__service__pb2.EchoMsg.SerializeToString,
                response_deserializer=discovery__service__pb2.EchoMsg.FromString,
                )


class DiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Keepalive(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Keepalive': grpc.stream_stream_rpc_method_handler(
                    servicer.Keepalive,
                    request_deserializer=discovery__service__pb2.KeepaliveRequest.FromString,
                    response_serializer=discovery__service__pb2.Servers.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=discovery__service__pb2.Server.FromString,
                    response_serializer=discovery__service__pb2.RegisterResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=discovery__service__pb2.EchoMsg.FromString,
                    response_serializer=discovery__service__pb2.EchoMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neptune.Discovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Discovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Keepalive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/neptune.Discovery/Keepalive',
            discovery__service__pb2.KeepaliveRequest.SerializeToString,
            discovery__service__pb2.Servers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neptune.Discovery/Register',
            discovery__service__pb2.Server.SerializeToString,
            discovery__service__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neptune.Discovery/Echo',
            discovery__service__pb2.EchoMsg.SerializeToString,
            discovery__service__pb2.EchoMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
