# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='discovery_service.proto',
  package='discovery',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x64iscovery_service.proto\x12\tdiscovery\x1a\x0b\x65rror.proto\"H\n\x10RegisterResponse\x12!\n\x05\x45rror\x18\x01 \x01(\x0b\x32\x12.Error.CommonError\x12\x11\n\tKeepalive\x18\x02 \x01(\x05\"\x1e\n\x10KeepaliveRequest\x12\n\n\x02Id\x18\x01 \x01(\x05\"\"\n\x06Server\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12\n\n\x02Id\x18\x02 \x01(\x05\"P\n\x07Servers\x12!\n\x05\x45rror\x18\x01 \x01(\x0b\x32\x12.Error.CommonError\x12\"\n\x07Servers\x18\x02 \x03(\x0b\x32\x11.discovery.Server2\x8d\x01\n\tDiscovery\x12\x42\n\tKeepalive\x12\x1b.discovery.KeepaliveRequest\x1a\x12.discovery.Servers\"\x00(\x01\x30\x01\x12<\n\x08Register\x12\x11.discovery.Server\x1a\x1b.discovery.RegisterResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[error__pb2.DESCRIPTOR,])




_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='discovery.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Error', full_name='discovery.RegisterResponse.Error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Keepalive', full_name='discovery.RegisterResponse.Keepalive', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=123,
)


_KEEPALIVEREQUEST = _descriptor.Descriptor(
  name='KeepaliveRequest',
  full_name='discovery.KeepaliveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='discovery.KeepaliveRequest.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=155,
)


_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='discovery.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='discovery.Server.Type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Id', full_name='discovery.Server.Id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=191,
)


_SERVERS = _descriptor.Descriptor(
  name='Servers',
  full_name='discovery.Servers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Error', full_name='discovery.Servers.Error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Servers', full_name='discovery.Servers.Servers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=273,
)

_REGISTERRESPONSE.fields_by_name['Error'].message_type = error__pb2._COMMONERROR
_SERVERS.fields_by_name['Error'].message_type = error__pb2._COMMONERROR
_SERVERS.fields_by_name['Servers'].message_type = _SERVER
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
DESCRIPTOR.message_types_by_name['KeepaliveRequest'] = _KEEPALIVEREQUEST
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['Servers'] = _SERVERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:discovery.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

KeepaliveRequest = _reflection.GeneratedProtocolMessageType('KeepaliveRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEEPALIVEREQUEST,
  '__module__' : 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:discovery.KeepaliveRequest)
  })
_sym_db.RegisterMessage(KeepaliveRequest)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), {
  'DESCRIPTOR' : _SERVER,
  '__module__' : 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:discovery.Server)
  })
_sym_db.RegisterMessage(Server)

Servers = _reflection.GeneratedProtocolMessageType('Servers', (_message.Message,), {
  'DESCRIPTOR' : _SERVERS,
  '__module__' : 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:discovery.Servers)
  })
_sym_db.RegisterMessage(Servers)



_DISCOVERY = _descriptor.ServiceDescriptor(
  name='Discovery',
  full_name='discovery.Discovery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=276,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='Keepalive',
    full_name='discovery.Discovery.Keepalive',
    index=0,
    containing_service=None,
    input_type=_KEEPALIVEREQUEST,
    output_type=_SERVERS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='discovery.Discovery.Register',
    index=1,
    containing_service=None,
    input_type=_SERVER,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOVERY)

DESCRIPTOR.services_by_name['Discovery'] = _DISCOVERY

# @@protoc_insertion_point(module_scope)
