# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import neptune_msg_pb2 as neptune__msg__pb2


class NeptuneMessageStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MessageStream = channel.stream_stream(
                '/neptune.NeptuneMessageStream/MessageStream',
                request_serializer=neptune__msg__pb2.NeptuneMessage.SerializeToString,
                response_deserializer=neptune__msg__pb2.NeptuneMessage.FromString,
                )


class NeptuneMessageStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MessageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeptuneMessageStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MessageStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MessageStream,
                    request_deserializer=neptune__msg__pb2.NeptuneMessage.FromString,
                    response_serializer=neptune__msg__pb2.NeptuneMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neptune.NeptuneMessageStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NeptuneMessageStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/neptune.NeptuneMessageStream/MessageStream',
            neptune__msg__pb2.NeptuneMessage.SerializeToString,
            neptune__msg__pb2.NeptuneMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
