# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neptune_msg.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neptune_msg.proto',
  package='neptune',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11neptune_msg.proto\x12\x07neptune\"O\n\x0eNeptuneMessage\x12,\n\x07MsgType\x18\x01 \x01(\x0e\x32\x1b.neptune.NeptuneMessageType\x12\x0f\n\x07Payload\x18\x03 \x01(\t*0\n\x12NeptuneMessageType\x12\x1a\n\x16NeptuneMessageTypeCall\x10\x00\x32_\n\x14NeptuneMessageStream\x12G\n\rMessageStream\x12\x17.neptune.NeptuneMessage\x1a\x17.neptune.NeptuneMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)

_NEPTUNEMESSAGETYPE = _descriptor.EnumDescriptor(
  name='NeptuneMessageType',
  full_name='neptune.NeptuneMessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NeptuneMessageTypeCall', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=111,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_NEPTUNEMESSAGETYPE)

NeptuneMessageType = enum_type_wrapper.EnumTypeWrapper(_NEPTUNEMESSAGETYPE)
NeptuneMessageTypeCall = 0



_NEPTUNEMESSAGE = _descriptor.Descriptor(
  name='NeptuneMessage',
  full_name='neptune.NeptuneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='neptune.NeptuneMessage.MsgType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='neptune.NeptuneMessage.Payload', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=109,
)

_NEPTUNEMESSAGE.fields_by_name['MsgType'].enum_type = _NEPTUNEMESSAGETYPE
DESCRIPTOR.message_types_by_name['NeptuneMessage'] = _NEPTUNEMESSAGE
DESCRIPTOR.enum_types_by_name['NeptuneMessageType'] = _NEPTUNEMESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NeptuneMessage = _reflection.GeneratedProtocolMessageType('NeptuneMessage', (_message.Message,), {
  'DESCRIPTOR' : _NEPTUNEMESSAGE,
  '__module__' : 'neptune_msg_pb2'
  # @@protoc_insertion_point(class_scope:neptune.NeptuneMessage)
  })
_sym_db.RegisterMessage(NeptuneMessage)



_NEPTUNEMESSAGESTREAM = _descriptor.ServiceDescriptor(
  name='NeptuneMessageStream',
  full_name='neptune.NeptuneMessageStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=161,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='MessageStream',
    full_name='neptune.NeptuneMessageStream.MessageStream',
    index=0,
    containing_service=None,
    input_type=_NEPTUNEMESSAGE,
    output_type=_NEPTUNEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEPTUNEMESSAGESTREAM)

DESCRIPTOR.services_by_name['NeptuneMessageStream'] = _NEPTUNEMESSAGESTREAM

# @@protoc_insertion_point(module_scope)
