# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bar.proto',
  package='bar',
  syntax='proto3',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\tbar.proto\x12\x03\x62\x61r\"\x1d\n\nBarRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x42\x61rResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2/\n\x03\x42\x61r\x12(\n\x03\x42\x61r\x12\x0f.bar.BarRequest\x1a\x10.bar.BarResponseB\x03\x90\x01\x01\x62\x06proto3')
)




_BARREQUEST = _descriptor.Descriptor(
  name='BarRequest',
  full_name='bar.BarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bar.BarRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_BARRESPONSE = _descriptor.Descriptor(
  name='BarResponse',
  full_name='bar.BarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bar.BarResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['BarRequest'] = _BARREQUEST
DESCRIPTOR.message_types_by_name['BarResponse'] = _BARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BarRequest = _reflection.GeneratedProtocolMessageType('BarRequest', (_message.Message,), {
  'DESCRIPTOR' : _BARREQUEST,
  '__module__' : 'bar_pb2'
  # @@protoc_insertion_point(class_scope:bar.BarRequest)
  })
_sym_db.RegisterMessage(BarRequest)

BarResponse = _reflection.GeneratedProtocolMessageType('BarResponse', (_message.Message,), {
  'DESCRIPTOR' : _BARRESPONSE,
  '__module__' : 'bar_pb2'
  # @@protoc_insertion_point(class_scope:bar.BarResponse)
  })
_sym_db.RegisterMessage(BarResponse)


DESCRIPTOR._options = None

_BAR = _descriptor.ServiceDescriptor(
  name='Bar',
  full_name='bar.Bar',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='Bar',
    full_name='bar.Bar.Bar',
    index=0,
    containing_service=None,
    input_type=_BARREQUEST,
    output_type=_BARRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BAR)

DESCRIPTOR.services_by_name['Bar'] = _BAR

Bar = service_reflection.GeneratedServiceType('Bar', (_service.Service,), dict(
  DESCRIPTOR = _BAR,
  __module__ = 'bar_pb2'
  ))

Bar_Stub = service_reflection.GeneratedServiceStubType('Bar_Stub', (Bar,), dict(
  DESCRIPTOR = _BAR,
  __module__ = 'bar_pb2'
  ))


# @@protoc_insertion_point(module_scope)
