# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo.proto',
  package='foo',
  syntax='proto3',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\tfoo.proto\x12\x03\x66oo\"\x1d\n\nFooRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x46ooResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2/\n\x03\x46oo\x12(\n\x03\x46oo\x12\x0f.foo.FooRequest\x1a\x10.foo.FooResponseB\x03\x90\x01\x01\x62\x06proto3')
)




_FOOREQUEST = _descriptor.Descriptor(
  name='FooRequest',
  full_name='foo.FooRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='foo.FooRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_FOORESPONSE = _descriptor.Descriptor(
  name='FooResponse',
  full_name='foo.FooResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='foo.FooResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['FooRequest'] = _FOOREQUEST
DESCRIPTOR.message_types_by_name['FooResponse'] = _FOORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FooRequest = _reflection.GeneratedProtocolMessageType('FooRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOOREQUEST,
  '__module__' : 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.FooRequest)
  })
_sym_db.RegisterMessage(FooRequest)

FooResponse = _reflection.GeneratedProtocolMessageType('FooResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOORESPONSE,
  '__module__' : 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.FooResponse)
  })
_sym_db.RegisterMessage(FooResponse)


DESCRIPTOR._options = None

_FOO = _descriptor.ServiceDescriptor(
  name='Foo',
  full_name='foo.Foo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='Foo',
    full_name='foo.Foo.Foo',
    index=0,
    containing_service=None,
    input_type=_FOOREQUEST,
    output_type=_FOORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOO)

DESCRIPTOR.services_by_name['Foo'] = _FOO

Foo = service_reflection.GeneratedServiceType('Foo', (_service.Service,), dict(
  DESCRIPTOR = _FOO,
  __module__ = 'foo_pb2'
  ))

Foo_Stub = service_reflection.GeneratedServiceStubType('Foo_Stub', (Foo,), dict(
  DESCRIPTOR = _FOO,
  __module__ = 'foo_pb2'
  ))


# @@protoc_insertion_point(module_scope)
