// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/neptune/nrpc/nrpc.proto

package nrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPC struct {
	Request              *Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response             *Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Sid                  uint32    `protobuf:"varint,3,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed4ce1002f6c713, []int{0}
}

func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (m *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(m, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RPC) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RPC) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

type Request struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Args                 []byte   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed4ce1002f6c713, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed4ce1002f6c713, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Response struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed4ce1002f6c713, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*RPC)(nil), "nrpc.RPC")
	proto.RegisterType((*Request)(nil), "nrpc.Request")
	proto.RegisterType((*Error)(nil), "nrpc.Error")
	proto.RegisterType((*Response)(nil), "nrpc.Response")
}

func init() { proto.RegisterFile("src/neptune/nrpc/nrpc.proto", fileDescriptor_eed4ce1002f6c713) }

var fileDescriptor_eed4ce1002f6c713 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x94, 0x49, 0xd3, 0xc7, 0xb6, 0x45, 0xb0, 0x07, 0x14, 0xc1, 0xa5, 0xe4, 0x42, 0x85, 0x44,
	0x2b, 0x81, 0xf8, 0x01, 0x10, 0x07, 0x6e, 0x68, 0x8f, 0xdc, 0x20, 0x59, 0x15, 0x24, 0x6a, 0x9b,
	0xb5, 0xfb, 0x1f, 0x7c, 0x32, 0xf2, 0x3a, 0x81, 0x5c, 0xa2, 0xc9, 0xce, 0x78, 0x66, 0x76, 0xe1,
	0x22, 0x48, 0xb3, 0xb5, 0xec, 0xe3, 0xc1, 0xf2, 0xd6, 0x8a, 0x6f, 0xf4, 0xb3, 0xf1, 0xe2, 0xa2,
	0xc3, 0x51, 0xc2, 0xf5, 0x17, 0x14, 0xf4, 0xf2, 0x88, 0x57, 0x30, 0x11, 0xfe, 0x3e, 0x70, 0x88,
	0x95, 0x59, 0x99, 0xf5, 0xfc, 0x76, 0xb9, 0x51, 0x29, 0xe5, 0x21, 0xf5, 0x2c, 0x5e, 0xc3, 0x54,
	0x38, 0x78, 0x67, 0x03, 0x57, 0x47, 0xaa, 0x3c, 0xee, 0x95, 0x79, 0x4a, 0x7f, 0x3c, 0x9e, 0x40,
	0x11, 0x3e, 0xdb, 0xaa, 0x58, 0x99, 0xf5, 0x92, 0x12, 0xac, 0xef, 0x61, 0xd2, 0x39, 0xe2, 0x19,
	0x8c, 0xf7, 0x1c, 0x3f, 0x5c, 0xab, 0x81, 0x33, 0xea, 0xfe, 0x10, 0x61, 0xf4, 0x26, 0xbb, 0xa0,
	0xe6, 0x0b, 0x52, 0x5c, 0xdf, 0x40, 0xf9, 0x24, 0xe2, 0x24, 0x91, 0x8d, 0x6b, 0x59, 0x9f, 0x94,
	0xa4, 0x38, 0xa5, 0xec, 0xc3, 0x4e, 0xf5, 0x33, 0x4a, 0xb0, 0x7e, 0x86, 0x69, 0xdf, 0x06, 0xcf,
	0x07, 0x7d, 0x8d, 0x5a, 0xfe, 0xf7, 0xbb, 0x84, 0x92, 0x93, 0x6d, 0xb7, 0xc8, 0x3c, 0x2f, 0xa2,
	0x49, 0x94, 0x99, 0x87, 0xd3, 0xd7, 0xc5, 0xf0, 0x7e, 0x3f, 0xc6, 0xbc, 0x8f, 0xf5, 0x7c, 0x77,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59, 0x35, 0x42, 0xea, 0x5d, 0x01, 0x00, 0x00,
}
